version: '3'
services:
  nginx-test:
    image:  nginx:mainline-alpine
    volumes:
      - ./temp/html:/usr/share/nginx/html:ro
  nginx-proxy:
    image:  test-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAINS=test.local=nginx-test
      - CERTBOT=nginx-test
    volumes:
      - ./temp/vhost.d:/etc/nginx/vhost.d:ro
      - ./temp/html:/usr/share/nginx/html:ro
      - ./temp/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nginx-test
  certbot:
    image:  test-certbot
    environment:
      - DOMAINS=test.local.com
      - EMAIL=wei.shi@boxinholding.com
      - STAGING=True
    volumes:
      - ./temp/html:/usr/share/nginx/html:rw
      - ./temp/letsencrypt:/etc/letsencrypt:rw
    depends_on:
      - nginx-proxy


networks:
  default:
    external:
      name: test_default